### ISSUE TITLE
Operator v2: tracking features

### ISSUE THREAD

**Issue by WanzenBug** [piraeusdatastore/piraeus-operator#334]
We've recently started work on [Operator v2](https://github.com/piraeusdatastore/piraeus-operator/tree/v2)

This is intended as a list of features that need to be ported from v1, or features we want to add in v2:

* [ ] Cluster Setup:
  * [x] Create controller
  * [x] Create satellites
  * [x] Register satellites
  * [x] Sync node labels to satellites
  * [x] Evict satellites
  * [ ] Add multiple NICs if multus is used
  * [x] Satellite set up using new LinstorSatelliteConfig resource with node selectors
  * [x] Include HA Controller by default
  * [x] Add shutdown guard, that automatically reconfigures DRBD for io-errors on node shutdown
  * [x] https://github.com/piraeusdatastore/piraeus-operator/issues/366
  * [x] https://github.com/piraeusdatastore/piraeus-operator/issues/447
* [ ] DRBD:
  * [x] Detect loader image to use per node
  * [x] Optionally use host network instead of pod network
  * [ ] Idea: rolling upgrades when node not in use?
* [x] CSI:
  * [x] Driver setup
  * [x] Restart when node labels change
  * [x] Test with s3 backup
* [ ] Packaging & Release
  * [x] Helm chart -> use https://github.com/arttor/helmify ?
  * [x] Upgrade from v1 guide #410 
    * [x] Migration script for most common cases
    * [x] DB migration from non-k8s backend #341 
---
Note: this list is not complete. If there is something to be added, please comment below

**Comment by WanzenBug** [comment]
> Consider using [Kustomize](https://kustomize.io/) as the default deployment tool

On that front, I can report that the [`v2` branch](https://github.com/piraeusdatastore/piraeus-operator/tree/v2) is already using kustomize, both as a way to deploy the operator and as a way to customize the actually deployed resources. Basically, you can attach kustomize patches to the resources managed by the operator.

We are still thinking about adding some form of Helm chart, since a lot of users are still used to that.

**Comment by bc185174** [comment]
Along with the registry, could we configure the image pull secrets, pull policy and image tag? Makes it simpler for end-users to automate upgrading the application. For instance, using `yq` to adjust the image tag in a Makefile. More than happy to help contribute as always.

```yaml
apiVersion: piraeus.io/v1
kind: LinstorCluster
metadata:
  name: linstorcluster
spec:
  imageSource: 
    repository: registry.example.com/piraeus
    tag: v1.10.0
    pullPolicy: IfNotPresent
    pullSecrets:
    - "SecretName"
```

**Comment by robinbraemer** [comment]
Nice work on v2 so far!
There is a problem with the `drbd-module-loader` init-container on [Talos](https://www.talos.dev/) nodes.
On Talos operating system we use  [extension](https://github.com/siderolabs/extensions/blob/main/storage/drbd/pkg.yaml) to add things like kernel modules and the directory structure is a little bit different.

I've deployed the operator using kustomize from the `config/default` directory and have created the following CRDs:

```yaml
apiVersion: piraeus.io/v1
kind: LinstorCluster
metadata:
  name: linstor-cluster
spec:
  nodeSelector:
    node-role.kubernetes.io/linstor: ""
---
apiVersion: piraeus.io/v1
kind: LinstorSatelliteConfiguration
metadata:
  name: all-satellites
spec:
  storagePools:
    - name: fs1
      filePool: {}
```

The `drbd-module-loader` init-container of the "node pod" tries to hostPath mount `/usr/lib/modules`, which does not exist on Talos making kubelet error:
```
MountVolume.SetUp failed for volume "usr-lib-modules" : hostPath type check failed: /usr/lib/modules is not a directory
```

FYI: On Talos `/usr/lib/` contains the following:
```sh
$ talosctl -n 100.64.6.90 list /usr/lib/
NODE          NAME
100.64.6.90   .
100.64.6.90   cryptsetup
100.64.6.90   engines-1.1
100.64.6.90   libaio.so
....many .so files
100.64.6.90   udev
100.64.6.90   xfsprogs

$ talosctl -n 100.64.6.90 list /lib/modules
NODE          NAME
100.64.6.90   .
100.64.6.90   5.15.86-talos
```

I can confirm I've installed the `drbd` and `drbd_transport_tcp` kernel modules from the [Talos drbd extension](https://github.com/siderolabs/extensions/blob/main/storage/drbd/pkg.yaml):
```sh
$ talosctl -n 100.64.6.90 read /proc/drbd
version: 9.2.0 (api:2/proto:86-121)
GIT-hash: 71e60591f3d7ea05034bccef8ae362c17e6aa4d1 build by @buildkitsandbox, 2023-01-11 12:22:06
Transports (api:18): tcp (9.2.0)
```

**Afterthoughts** (I'm not an expert)

The `/usr/lib/modules` directory is typically where the Linux kernel stores the loadable modules (or drivers) that can be loaded into the kernel at runtime. This directory is typically only present on systems that use a monolithic kernel, which includes all the necessary drivers and modules built directly into the kernel.

In contrast, Talos is a kernel that uses a modular design, which means that it loads only the necessary modules at runtime. It does not have a `/usr/lib/modules` directory as it does not store the kernel modules on disk(?)

Because the script is trying to mount the `/usr/lib/modules` directory, it will not work as expected on a Talos machine. We may need to modify the script or can remove the init-container, but I think having some init container that runs the recommended `modprobe drbd usermode_helper=disabled` is very helpful to do on every linstor node.

**refs:**
There are efforts on documenting how to use piraeus-operator on the Talos website: https://github.com/siderolabs/talos/pull/6426
which will help increase awareness of this great storage project.


@DJAlPee - Got this already working on Talos, but only the main branch piraeus v1 version.
@cf-sewe @frezbo @smira - might be able to help support piraeus on this topic

**Comment by frezbo** [comment]
just a note, loading modules on talos is disabled, since talos is a configuration driven os, module loading and it's parameters are specified in the machine config, so I guess having an option to disable the init container makes more sense

**Comment by WanzenBug** [comment]
This sounds like the exact use-case we now have [`patches`](https://github.com/piraeusdatastore/piraeus-operator/blob/v2/docs/reference/linstorsatelliteconfiguration.md#specpatches) for:

```
apiVersion: piraeus.io/v1
kind: LinstorSatelliteConfiguration
metadata:
  name: no-loader
spec:
  patches:
    - target:
        kind: Pod
        name: satellite
      patch: |
        apiVersion: v1
        kind: Pod
        metadata:
          name: satellite
        spec:
          initContainers:
          - name: drbd-module-loader
            $patch: delete
```

This disables the init container on all nodes.

**Comment by DJAlPee** [comment]
This seems to be a pretty nice approach!
In v1 I used `operator.satelliteSet.kernelModuleInjectionMode=None` in helm, which seems to have the same effect, but is deprecated (But why?).

**Comment by WanzenBug** [comment]
> but is deprecated (But why?).

Because you almost always want to use `DepsOnly`. I don't know if this would work on Talos, but it should ensure that all the other "useful" mods are loaded if they are available. So `dm-thin`, `dm-crypt`, etc...

**Comment by DJAlPee** [comment]
> Because you almost always want to use `DepsOnly`. [...]
As @frezbo stated, module loading is disabled in Talos. So we have the "almost" case here 😉 
I will update the documentation draft to use `None`, when using the v1 operator. I hope, you keep this functionality for v1 and remove it only in v2 😉

**Comment by WanzenBug** [comment]
Operator v2 is released.
